[theme]
base = "dark"
primaryColor = "#76ABAE"
backgroundColor = "#31363F"
secondaryBackgroundColor = "#222831"
textColor = "#f8fafc"
font = "sans serif"

[server]
port = 8501
headless = true

[browser]
gatherUsageStats = false
